port : "8060"

db: 
   host: "localhost"
   port: "5050"
   user: "jemal"
   dbname: "short_url"
   sslmode: "disable"

domain: "http://localhost/"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
